// src/components/Counter-solid.tsx
import { createSignal } from 'solid-js'

export default function Counter() {
	const [count, setCount] = createSignal(0)
	return (
		<div>
			<h1>this is solid counter</h1>
			<h2>{count()}</h2>
			<button onClick={() => setCount(count() + 1)}>Increment</button>
			<button onClick={() => setCount(count() - 1)}>Decrement</button>
		</div>
	)
}

// src/components/Counter.tsx
import { useState } from 'react'

export default function Counter() {
	const [count, setCount] = useState(0)
	return (
		<div>
			<h1>this is react counter</h1>
			<h2>{count}</h2>
			<button onClick={() => setCount(count + 1)}>Increment</button>
			<button onClick={() => setCount(count - 1)}>Decrement</button>
		</div>
	)
}
